package com.demo.demo.processor;

import java.util.Map;

import org.springframework.batch.infrastructure.item.ItemProcessor;
import org.springframework.stereotype.Component;

import lombok.extern.slf4j.Slf4j;

@Slf4j
@Component("complexLedgerTaxProcessor")
public class ComplexLedgerTaxProcessor implements ItemProcessor<Map<String, Object>, Map<String, Object>> {

    @Override
    public Map<String, Object> process(Map<String, Object> item) throws Exception {
        
        // 1. You still receive the Map generated by your Dynamic File/DB Reader
        String description = (String) item.get("description");
        String entryId = (String) item.get("entryId");
        
        // 2. Map the fields (replicating what the direct-map did)
        item.put("id", entryId != null ? entryId : 0);
        item.put("item_name", description != null ? description : "UNKNOWN ITEM");
        
        // 3. Add your complex Java business logic!
        if (description != null && description.toUpperCase().contains("CAKE")) {
            item.put("tax_rate", 0.08);
            item.put("category", "BAKED_GOODS");
        } else {
            item.put("tax_rate", 0.00);
            item.put("category", "SUPPLIES");
        }

        return item; // Hand it off to the Dynamic Writer!
    }
}